In [33]:
import numpy as np
y_1 = np.zeros((12,13), dtype=int)
print("_________________________")
print(y_1)
##Trying to visualise the radios as a numpy meshgrid

_________________________
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [34]:
# print(y_1[0][1])
# y_1[y coord][x coord] = 4
y_1[1][2] = 0
#___[y]_[x]
print(y_1)

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [51]:
li = [(1,1),(1,11),(3,4),(3,6),(3,8),(5,4),(5,6),(5,8),(6, 1),(6, 11),
      (7,4),(9,4), (9,6), (9,8),(11,1), (11, 4), (11, 8), (11, 11)]
#format is standard coordinate system --> (x,y)
# print(len(li))

# print(li[0][0])
# print(li[0][1])
# listy = np.array(li)
# print(listy)
# print(listy[0][1])
print(len(li))


18


In [52]:
# li = [(1,1),(1,10),(3,3),(3,5),(3,7),(5,3),(5,5),(5,7),(6, 1),(6, 10),
#       (7,4),(9,4), (9,6), (9,8),(11,1), (11, 4), (11, 8), (11, 11)]
y_1 = np.zeros((13,12), dtype=int)
for i in range(0, 18):
    
    y_1[li[i][1]][li[i][0]] = 1

print(y_1)
## The radio grid in form of a matrix. The ones represent 
## 

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [55]:
## All the different combinations of 6 radios 
from itertools import combinations
comb = combinations(li, 6)
comb = list(comb)
print(len(comb))

18564


In [61]:
for i in range(12:
    for j in range(13):
        print(y_1[i][j])
        
        
    

0
0
0
0
0
0
0
0
0
0
0
0


IndexError: index 12 is out of bounds for axis 0 with size 12